### ISSUE TITLE
Make it work with nested uls

### ISSUE THREAD

**Issue by davidspiess** [kamens/jQuery-menu-aim#10]
http://stackoverflow.com/questions/15259950/implementing-jquery-menu-aim

**Comment by m-pokrovskii** [comment]
No. It's plugin functionality. If you will try to hover some row-element nothing happened.
For fix this you must comment 130 line. 

```
if (row == activeRow) {
// return;
}
```

It's totally dirty hack, but it's work.

---

English is not my native language. Sorry.

**Comment by kamens** [comment]
If the nested submenus are all of equal height, this can be accomplished by setting up multiple jquery menu-aim integration points (call .menuAim on each level of menu that has a submenu "below" it).

If the nested submenus are not all of equal height, this plugin/algorithm is not a great choice due to the problems explained here: http://michelf.ca/blog/2005/mac-sub-menus/
