### ISSUE TITLE
Demo is broken.

### ISSUE THREAD

**Issue by entropie** [kamens/jQuery-menu-aim#16]
Probably because of the latest github changes.

**Comment by chuntley** [comment]
Also it would be great if the demo could feature a barebones example instead of using bootstrap. That way it would be much easier to grab the code and implement it into a non-bootstrap website.

**Comment by natepers** [comment]
Demo is still broken.
Definitely looks github related.

Console Errors------------------------------------------

Refused to execute script from 'https://raw.github.com/kamens/jQuery-menu-aim/master/example/js/jquery-1.9.1.min.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled. htmlpreview.github.io/:1
Refused to execute script from 'https://raw.github.com/kamens/jQuery-menu-aim/master/jquery.menu-aim.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled. htmlpreview.github.io/:1
Refused to execute script from 'https://raw.github.com/kamens/jQuery-menu-aim/master/example/js/bootstrap.min.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled. htmlpreview.github.io/:1
Uncaught ReferenceError: $ is not defined htmlpreview.github.io/:3
(anonymous function) htmlpreview.github.io/:3

**Comment by kamens** [comment]
Demo looks fixed to me now -- can you confirm plz?
